// examples/react/useWebOcr.ts
/**
 * React Hook 示例
 *
 * npm i webocr
 * vite.config.ts → import { webocr } from 'webocr/vite'; plugins: [webocr()]
 * 模型 / 字典 / wasm 已打在包内，默认走 /webocr/
 */
import { useEffect, useRef, useState } from "react";
import { createWebOcr, type OcrProgress, type OcrResult, type WebOcr } from "webocr";

export function useWebOcr() {
  const ocrRef = useRef<WebOcr | null>(null);
  const [ready, setReady] = useState(false);
  const [provider, setProvider] = useState("");
  const [progress, setProgress] = useState<OcrProgress | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const ocr = await createWebOcr({
          onProgress: (p) => {
            if (!cancelled) setProgress(p);
          },
        });
        if (cancelled) {
          ocr.dispose();
          return;
        }
        ocrRef.current = ocr;
        setProvider(ocr.executionProvider);
        setReady(true);
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
        }
      }
    })();

    return () => {
      cancelled = true;
      ocrRef.current?.dispose();
      ocrRef.current = null;
    };
  }, []);

  async function recognize(input: File | Blob): Promise<OcrResult> {
    if (!ocrRef.current) throw new Error("OCR 未就绪");
    return ocrRef.current.recognize(input);
  }

  return { ready, provider, progress, error, recognize };
}

// examples/vue/UseWebOcr.vue
<script setup lang="ts">
/**
 * Vue 3 调用示例
 *
 * npm i webocr
 * vite.config.js / .ts → plugins: [webocr()]
 * 模型 / 字典 / wasm 已打在包内，默认走 /webocr/
 */
import { onMounted, onUnmounted, ref } from "vue";
import { createWebOcr, type OcrResult, type WebOcr } from "webocr";

const status = ref("初始化中…");
const text = ref("");
const busy = ref(false);
let ocr: WebOcr | null = null;

onMounted(async () => {
  ocr = await createWebOcr({
    onProgress: (p) => {
      status.value = `${p.message} (${p.percent}%)`;
    },
  });
  status.value = `就绪 · ${ocr.executionProvider}`;
});

onUnmounted(() => {
  ocr?.dispose();
  ocr = null;
});

async function onFileChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0];
  if (!file || !ocr) return;
  busy.value = true;
  try {
    const result: OcrResult = await ocr.recognize(file);
    text.value = result.lines.map((l) => l.text).join("\n");
  } catch (err) {
    status.value = err instanceof Error ? err.message : String(err);
  } finally {
    busy.value = false;
  }
}
</script>

<template>
  <div>
    <p>{{ status }}</p>
    <input type="file" accept="image/*" :disabled="busy || !ocr" @change="onFileChange" />
    <pre>{{ text }}</pre>
  </div>
</template>
